# Generated by Django 3.2.3 on 2021-06-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_nm', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Emploee Name')),
                ('emp_id', models.PositiveIntegerField(default=0, verbose_name='Emploee Ids')),
                ('emp_em', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Employee Email')),
                ('emp_cno', models.IntegerField(default=0, verbose_name='Emploee Contact NO')),
                ('emp_add1', models.TextField(default='', verbose_name='Emploee Adress1')),
                ('emp_add2', models.TextField(default='', verbose_name='Emploee Adress2')),
            ],
        ),
    ]
